/* Gravemark — tools/grok-prompts.js
   Generates GROK-PROMPTS.md: one ready-to-paste prompt per MISSING asset.

   Written for a text-to-image tool that produces ONE image per request and
   cannot make sprite strips or aligned layers. It scans art/ for what is
   actually absent or still filler, so the list shrinks as art lands.

       node tools/grok-prompts.js > GROK-PROMPTS.md
*/
"use strict";
const fs = require("fs");
const path = require("path");
const { load } = require("./harness");

const GM = load({ quiet: true });
GM.startSeason("s_none");

const ART = path.join(__dirname, "..", "art");
function have(key) {
  return fs.existsSync(path.join(ART, key + ".png")) ||
         fs.existsSync(path.join(ART, key + ".jpg"));
}

/* A sheet that is present but only one frame wide is a still image wearing an
   animation's clothes: it loads and plays and nothing moves. Those are the
   keys the animation section asks for. */
function isStill(spec) {
  if (!have(spec.key) || spec.kind !== "sheet") return false;
  try {
    const buf = fs.readFileSync(path.join(ART, spec.key + ".png"));
    /* PNG IHDR width lives at bytes 16-19, big-endian. Cheaper and more
       dependable here than pulling in an image library. */
    const w = buf.readUInt32BE(16);
    return Math.max(1, Math.round(w / spec.w)) < 2;
  } catch (e) { return false; }
}

const out = [];
const W = s => out.push(s);

const MATERIAL = {
  low:  "rusted iron, lashed cord, chipped bone, improvised and much-repaired",
  mid:  "cleanly forged steel, fitted leather, carved bone, the work of a real smith",
  high: "reliquary-grade: blackened steel with gold inlay, names cut into every surface, relic-bone fittings"
};

/* ---------------------------------------------------------------- header */
W("# Gravemark — Grok prompt pack");
W("");
W("_Generated by `tools/grok-prompts.js` from the live manifest and a scan of `art/`._");
W("_Regenerate after every delivery — the list shrinks as art lands._");
W("");

/* doll/ is superseded by the rig; parts/ has its own brief (GROK-PARTS.md). */
const gaps = GM.ART.filter(a => !have(a.key) && !a.key.startsWith("doll/") && !a.key.startsWith("parts/"));
const stillCount = GM.ART.filter(isStill).length;
W(`**${gaps.length} assets missing, and ${stillCount} more that exist but do not move.**`);
W("");

W("## Read this first — it is why the last three packs did not work");
W("");
W("Grok makes **one image per prompt**. It cannot produce:");
W("");
W("- **Sprite strips.** Every sheet so far came back as the same pose copied eight times. Do not ask for strips. Ask for one pose; the game now reads frame count from the image itself, so a single frame is valid art and installs cleanly.");
W("- **Aligned paper-doll layers.** Three attempts returned item illustrations on white cards instead of gear drawn onto the body. There is no longer any gear to draw: a hero is a whole unit, and each class needs exactly one finished figure (section 1).");
W("");
W("### Rules for every prompt below");
W("");
W("1. **One image, one subject.** No grids, no sheets, no multiple views, no turnarounds.");
W("2. **Flat magenta background, `#FF00FF`.** Say it explicitly. Nothing in this game's palette is magenta, so the installer keys it out cleanly. Do not ask for transparency — it comes back as a white card, and a white card on a dark backdrop is a bright rectangle.");
W("3. **No text.** No labels, captions, letters, numbers, signature or watermark. Rune glyphs are the sole exception and must be invented marks, not real letters.");
W("4. **Exact pixel size** is given per asset. Square unless stated.");
W("5. **Full subject in frame**, small margin, nothing cropped at the edges.");
W("");
W("Paste the style block, then one asset prompt.");
W("");
W("```");
W(`STYLE: hand-painted 2D game art, painterly with visible brush texture. Cold, damp,
cut stone — a working graveyard that has been working far too long. Weathered granite,
wet earth, guttering lamplight, sorted bone. NOT vector, NOT pixel art, NOT 3D render,
NOT cartoon, NOT anime.

LIGHT: one low warm key source against cold blue-grey ambient fill, rim light to
separate the subject from the ground.

VALUE: dark overall, narrow bright range kept for bone, metal and lamplight. The
silhouette must read at 25% scale.

COLOUR: desaturated blue-grey base (#0c0d10 to #3d4454), exactly ONE saturated accent.
Bone #e6e0cf is the brightest neutral. Gold #d9b45c is the only metal accent.

BACKGROUND: flat solid magenta #FF00FF, edge to edge, no gradient, no shadow cast onto
it, no vignette, no border, no frame, no card.

NO text, letters, numbers, watermark, signature or logo anywhere in the image.`);
W("```");
W("");

/* ---------------------------------------------------------------- sections */
function table(rows) {
  W("| key | size | prompt |");
  W("|---|---|---|");
  rows.forEach(r => W(`| \`${r.key}\` | ${r.size} | ${r.prompt} |`));
  W("");
}

/* 1. class looks — one figure per class, highest value */
const looks = gaps.filter(a => a.key.indexOf("actor/look-") === 0);
if (looks.length) {
  W("---");
  W("");
  W("## 1. Class looks — do these first  _(" + looks.length + ")_");
  W("");
  W("**A hero is a whole unit.** There is no equipment: hiring a Reaver gives you a Reaver, sword and leathers and all, and nothing is ever taken off. So each class needs exactly ONE finished standing figure. The game tints the shared hero painting to the class colour until its own look arrives, and swaps the moment it does.");
  W("");
  W("All five are the **same world and the same scale**: wiry, weather-beaten gravediggers-turned-soldiers, hooded, oilcloth and leather, faces in shadow. **Standing, facing RIGHT, full body, feet near the bottom of the frame.**");
  W("");
  W("> Upload `art/actor/hero-idle.png` with the prompt and say *\"same proportions and footing as this reference, facing right\"*. That is the single biggest thing you can do to keep the five consistent.");
  W("");
  table(looks.map(a => {
    const id = a.key.replace("actor/look-", "");
    const c = GM.CLASS_BY_ID[id] || {};
    const ch = GM.Rig.CHARS.find(x => x.id === id) || {};
    return {
      key: a.key, size: `${a.w}×${a.h}`,
      prompt: `Full-body standing figure facing right, hooded, face in shadow: ${ch.label || c.name}. Carrying ${c.weapon ? "a " + c.weapon.fam : "their weapon"} at rest. Same proportions and footing as the reference. Feet near the bottom edge. Flat magenta #FF00FF background.`
    };
  }));
}

/* 1b. animation — the thing eight deliveries have not produced */
const stills = GM.ART.filter(isStill);
if (stills.length) {
  const pick = k => stills.filter(a => a.key.indexOf(k) === 0);
  const heroAnim = pick("actor/hero-");
  const monAnim = pick("mon/").filter(a => /-(attack|death)$/.test(a.key));

  W("---");
  W("");
  W("## 1b. Animation — read this, it is why eight packs produced none");
  W("");
  W(`**${stills.length} sheets are currently a single still image.** They load and play and nothing moves. Every previous delivery asked for "an 8-frame sheet" and returned the same pose copied eight times.`);
  W("");
  W("**Do not ask for a sheet. Ask for individual poses, numbered.**");
  W("");
  W("The game reads frame count from the image's own width, so a **3-frame** animation is completely valid art. Three real key poses beat eight identical ones. Deliver separate files:");
  W("");
  W("```");
  W(`  actor/hero-attack-sword-1.png     wind-up
  actor/hero-attack-sword-2.png     the strike landing
  actor/hero-attack-sword-3.png     recovery`);
  W("```");
  W("");
  W("and I stitch them into the strip the game wants:");
  W("");
  W("```bash");
  W("python3 tools/make-sheet.py <your-folder>");
  W("```");
  W("");
  W("**The one rule that makes or breaks this:** every frame of an action must be the *same character in the same place* — same size, same footing, same distance from the camera. Only the pose changes. Upload frame 1 as a reference image when prompting frame 2, and say *\"identical character, identical framing and scale, only the pose changes\"*. Without that they come back as three different drawings and the animation strobes.");
  W("");
  W("Priority order: the hero's attack swings first (they fire on every hit, so they are the most visible motion in the game), then monster attack and death, then walk cycles.");
  W("");
  W("| key | frames wanted | what each frame is |");
  W("|---|---|---|");
  const POSE = {
    attack: "1 wind-up, weapon drawn back &middot; 2 the strike landing, fully committed &middot; 3 recovery, settling back",
    cast:   "1 gathering, hands drawing in &middot; 2 the release, light leaving the hands &middot; 3 settling",
    walk:   "1 contact, forward foot down &middot; 2 passing, legs together &middot; 3 opposite contact",
    run:    "1 drive, hard lean &middot; 2 airborne, both feet off &middot; 3 opposite drive",
    idle:   "1 settled &middot; 2 the breath in, chest and shoulders lifted",
    hit:    "1 the flinch, head snapped back &middot; 2 recovering",
    death:  "1 the buckle, legs going &middot; 2 falling &middot; 3 down and still on the ground"
  };
  function poseFor(key) {
    const m = key.match(/-(attack|cast|walk|run|idle|hit|death)(-\w+)?$/);
    return POSE[m ? m[1] : "idle"] || POSE.idle;
  }
  function framesFor(key) { return /-(idle|hit)$/.test(key) ? 2 : 3; }
  heroAnim.concat(monAnim).slice(0, 60).forEach(a => {
    W(`| \`${a.key}\` | ${framesFor(a.key)} | ${poseFor(a.key)} |`);
  });
  W("");
  if (stills.length > heroAnim.length + monAnim.length) {
    W(`_${stills.length - heroAnim.length - monAnim.length} further still sheets (bosses, the revenant, remaining monster states) follow the same pattern — same poses, same numbering._`);
    W("");
  }
}

/* 4. monsters */
const mons = gaps.filter(a => a.key.indexOf("mon/") === 0);
if (mons.length) {
  W("---");
  W("");
  W("## 4. Monsters  _(" + mons.length + ")_");
  W("");
  W("**Facing LEFT** (they face the hero). One pose per image — no strips. Full body, feet near the bottom edge.");
  W("");
  const MON = {
    shambler:"a corpse risen out of habit rather than malice, grave-dirt, slack limbs, no weapon",
    gravedog:"a long starved dog, too many ribs showing, soil packed under its claws",
    digger:"a living body-snatcher in an oilcloth apron with a spade and a sack, furious at the interruption",
    bonepile:"a heap of sorted bones assembled wrong — too many femurs, one skull on top",
    mourner:"a veiled figure in soaked black crepe, hands empty, drifting just above the ground",
    chill:"a barrow-cold shape, more frost-rime outline than body, pale ice blue",
    drowned:"a choirboy long underwater, robes heavy with silt, mouth open on a note that never ends",
    bellwright:"a hunched bell-founder carrying a cracked bronze bell",
    ashwalker:"a body still burning as it walks, ash sloughing off with every step",
    pyrecult:"a robed cultist with a censer of live coals, face masked in beaten copper",
    stonewake:"a grave marker turned to face you, granite limbs grinding",
    reliquary:"an open empty reliquary casket walking on brass legs, void-purple glow inside",
    vigilant:"a tall watcher in funeral dress carrying a lantern that gives no light",
    unnamed:"a figure whose face will not hold still, features sliding off",
    threshold:"an enormous armoured gate-warden of fused stone and bone, barring the way"
  };
  const STATE = {
    idle:"standing still, weight settled",
    attack:"mid-strike, committed, the blow landing",
    hit:"recoiling from a blow, head snapped back",
    death:"collapsing, going down"
  };
  table(mons.map(a => {
    const m = a.key.match(/mon\/(\w+)-(\w+)$/);
    const arch = GM.MONSTER_BY_ID[m[1]] || {};
    return {
      key: a.key, size: `${a.w}×${a.h}`,
      prompt: `${(MON[m[1]] || arch.name || m[1])}, ${STATE[m[2]] || m[2]}. Facing LEFT, full body, feet near the bottom edge. ${GM.ELEM_META[arch.elem] ? GM.ELEM_META[arch.elem].label + " accent colour." : ""} Flat magenta #FF00FF background.`
    };
  }));
}

/* 5. backdrops */
const bgs = gaps.filter(a => a.key.indexOf("bg/") === 0);
if (bgs.length) {
  W("---");
  W("");
  W("## 5. Backdrops  _(" + bgs.length + ")_");
  W("");
  W("**Opaque — these are the only assets with a real background, so no magenta here.** Wide 1280×720 paintings. The figures stand on a ground line at about 82% height, so keep the lower fifth simple and uncluttered; it gets drawn over. Nothing important dead-centre.");
  W("");
  table(bgs.map(a => {
    const n = parseInt(a.key.split("-")[1], 10);
    const r = GM.REALMS[n - 1] || {};
    return {
      key: a.key, size: `${a.w}×${a.h}`,
      prompt: `Wide desolate landscape: **${r.name}**. ${r.flavour || ""} Empty of figures. Low horizon, heavy sky, cold light. Lower fifth of the frame kept simple. Opaque painting, no magenta.`
    };
  }));
}

/* 6. icons / ui / frames */
const chrome = gaps.filter(a => /^(icon|ui|frame)\//.test(a.key));
if (chrome.length) {
  W("---");
  W("");
  W("## 6. Icons, chrome and frames  _(" + chrome.length + ")_");
  W("");
  W("Lowest priority — the interface is CSS today and does not draw these yet. Small symbolic marks, readable at 24px, one accent colour each.");
  W("");
  table(chrome.map(a => ({
    key: a.key, size: `${a.w}×${a.h}`,
    prompt: `${a.label || a.key.split("/").pop().replace(/-/g, " ")} — a small symbolic carved-stone-and-metal icon, single accent colour, readable at 24 pixels, no text. Flat magenta #FF00FF background.`
  })));
}

W("---");
W("");
W("## Delivery");
W("");
W("- One PNG per key, named exactly as the key: `mon/shambler-idle` → `mon/shambler-idle.png`.");
W("- Any size is accepted if the aspect is right — the installer will not resize, so hitting the listed pixel size exactly avoids a rejection.");
W("- Magenta backgrounds are keyed out automatically on install; a stray magenta fringe is fine.");
W("- Zip the `art/` tree and send it. Partial deliveries are fine and land the same day.");
W("");
W("**If only one thing gets made next, make `actor/look-reaver`.** It proves the class-look approach end to end in a single image, and I can tell you within a minute of receiving it whether it works.");

console.log(out.join("\n"));
