/* Gravemark — tools/grok-parts.js
   Generates GROK-PARTS.md: the brief for painting characters as separate body
   parts, which is what the skeletal animator wears.

   This is the ask that replaces "animate this". An image generator cannot
   animate, but it CAN paint one part of a figure at a time from a reference
   painting — and once the parts exist, one rig and one set of keyframes move
   every character in the game the way Path of Idle moves.

       node tools/grok-parts.js > GROK-PARTS.md
*/
"use strict";
const fs = require("fs");
const path = require("path");
const { load } = require("./harness");

const GM = load({ quiet: true });
GM.startSeason("s_none");

const ART = path.join(__dirname, "..", "art");
const have = k => fs.existsSync(path.join(ART, k + ".png")) || fs.existsSync(path.join(ART, k + ".jpg"));

const out = [];
const W = s => out.push(s);
const pct = f => Math.round(f * 100) + "%";

const parts = GM.ART.filter(a => a.kind === "part" && !have(a.key));
const byChar = {};
parts.forEach(a => (byChar[a.charId] = byChar[a.charId] || []).push(a));

/* ------------------------------------------------------------------ head */
W("# Gravemark — parts brief");
W("");
W("_Generated by `tools/grok-parts.js` from the rig tables and a live scan of `art/`. Regenerate after every delivery._");
W("");
W(`**${parts.length} parts across ${Object.keys(byChar).length} characters.** Tiered — Tier 1 alone puts a fully animated, gear-visible hero in the game.`);
W("");

W("## What this is, and why it is the ask that finally works");
W("");
W("Path of Idle's characters are painted **once, as separate body parts**, and a bone rig moves the parts. The art never changes; the skeleton does. That rig is now built into Gravemark, with its animations — idle, five weapon swings, hit, death, walk, plus monster attacks — authored in code. What it is missing is the parts to wear.");
W("");
W("An image generator cannot animate. But it can absolutely **paint one piece of a figure from a reference painting**, and that is all this brief asks for. Every part is a single still image. No sheets, no frames, no motion — the motion is already done.");
W("");
W("Once the hero's parts exist, **equipped gear becomes visible on the animated character**: the hero is painted at three gear bands (low / mid / high) and the game swaps the set to match what the squad is wearing.");
W("");

W("## The convention — every part follows this exactly");
W("");
W("1. **Attach the character's reference painting** to every prompt. The part must match it in style, lighting, colour and scale — it is a *crop* of that figure, not a new drawing.");
W("2. **Paint the part UPRIGHT, exactly as it sits on the reference in its resting pose.** Do not rotate it, straighten it, or pose it. The rig rotates parts itself; at rest it applies no rotation at all, which is why \"as it appears on the reference\" is the whole instruction.");
W("3. **Only that part.** A forearm is elbow-to-fingertips and nothing else. No shoulder, no shadow of the torso, no ground.");
W("4. **Fill the canvas** given for the part, with the named **joint at the given position**. The joint is where the bone pivots — the shoulder for an upper arm, the hips for the torso — and the rig hangs the part from that exact point. Get this wrong and the arm detaches at the shoulder when it swings.");
W("5. **Flat magenta `#FF00FF` background**, edge to edge. Never ask for transparency; it comes back as a white card.");
W("6. **No text, no watermark, no border.**");
W("");
W("Near-side parts (`_f`) are the ones closer to the viewer. Far-side parts (`_b`) are the same limb on the other side of the body — paint them a touch darker, they are further from the light.");
W("");

W("### The prompt template");
W("");
W("```");
W(`[attach the reference painting]

From the attached reference painting of <character>, paint ONLY <part description>,
exactly as it appears on the reference: same style, same lighting, same colours, same
scale, upright, not re-posed. Nothing else of the body in the image.

Crop it to fill a <W>x<H> pixel canvas, with <joint> positioned at <X%> across and
<Y%> down the canvas.

Flat solid magenta #FF00FF background edge to edge. No text, no watermark, no border.`);
W("```");
W("");

W("## Style block — paste above every prompt");
W("");
W("```");
W(`Hand-painted 2D game art, painterly with visible brush texture. Cold, damp, cut stone.
NOT vector, NOT pixel art, NOT 3D render, NOT cartoon.
One low warm key light against cold blue-grey ambient, rim light on the edges.
Dark overall; bone #e6e0cf is the brightest neutral; ONE saturated accent per character.
This image is a CROP OF THE ATTACHED REFERENCE and must match it exactly.`);
W("```");
W("");

/* ------------------------------------------------------------------ tiers */
function charBlock(charId, note) {
  const list = byChar[charId];
  if (!list || !list.length) return 0;
  const ref = list[0].ref;
  const refOk = ref && have(ref);
  W(`### \`${charId}\` — ${list.length} parts`);
  W("");
  W(`**Reference:** ${refOk ? "`art/" + ref + ".png` (exists — attach it)" : "`" + ref + "` — **not painted yet**: paint this character's idle first, then cut parts from it"}`);
  if (note) { W(""); W(note); }
  W("");
  W("| key | canvas | joint | at | paint only |");
  W("|---|---|---|---|---|");
  list.forEach(a => {
    W(`| \`${a.key}\` | ${a.w}×${a.h} | ${a.joint} | ${pct(a.pivot.x)} across, ${pct(a.pivot.y)} down | ${a.label.split(" — ").pop()} |`);
  });
  W("");
  return list.length;
}

function tier(n, title, why, ids, notes) {
  W("---");
  W("");
  W(`## Tier ${n}: ${title}`);
  W("");
  W(why);
  W("");
  let total = 0;
  ids.forEach(id => { total += charBlock(id, notes && notes[id]); });
  return total;
}

let total = 0;

total += tier(1, "The hero at mid tier, and the five weapons",
  "Do this first. Eleven body parts and five weapons put a fully animated hero in the game with a visible weapon — every swing, hit and death already authored. The reference painting is the mid-tier band, so these are the most faithful crops of all.\n\n**Make `parts/hero-mid/torso` alone as a test.** One image proves the crop, the scale and the pivot before the other fifteen are made.",
  ["hero-mid", "weapon"],
  { weapon: "Weapons are painted **vertically, grip near the bottom, business end at the top**, as if held point-up at rest. The reference for each is its item icon: `art/item/<family>-mid.png`. No hand." });

total += tier(2, "The hero's other two gear bands",
  "This is what makes equipment show on the character. Same figure, same proportions, same pivots — only the gear changes. Low tier is rusted, lashed and improvised; high tier is reliquary-grade with gold inlay and names cut into the metal. Use the same reference and describe the band's materials in the prompt.",
  ["hero-low", "hero-high"]);

const humanoidMon = GM.MONSTERS.filter(m => GM.Rig.forChar(m.id).id === "humanoid").map(m => m.id);
total += tier(3, "The revenant and the humanoid monsters",
  "All of these share the hero's skeleton, so the same eleven parts, the same joints, the same swing. The revenant matters most: it is the player's own dead squad standing up, and it should read as the hero, corrupted.",
  ["revenant"].concat(humanoidMon));

const otherMon = GM.MONSTERS.filter(m => GM.Rig.forChar(m.id).id !== "humanoid").map(m => m.id);
total += tier(4, "Quadruped and mass-type monsters",
  "The grave dog is a four-legged rig (body, neck, head, tail, four legs). Bone piles, turned stones and walking caskets are a two-part mass: the body, and the one feature on top that moves.",
  otherMon);

total += tier(5, "Bosses",
  "One set each. Bosses are seen once every tenth depth, so these are last — but a boss that swings is a very different event from a boss that stands still.",
  GM.BOSSES.map(b => b.id));

/* ------------------------------------------------------------------ delivery */
W("---");
W("");
W("## Delivery");
W("");
W(`- **${total} images** across five tiers. Partial deliveries land the same day: a finished Tier 1 is an animated hero.`);
W("- One PNG per part, named exactly as the key: `parts/hero-mid/torso.png`. Keep the folder structure.");
W("- Exact canvas sizes matter — the rig positions each part by its pivot, and the pivot is a fraction of the canvas.");
W("- Magenta is keyed out on install. Do not deliver on white or transparent.");
W("- Zip and send. `python3 tools/art-install.py <folder>` installs; the rig picks the parts up automatically and drops back to the whole-figure painting for any character whose set is incomplete.");
W("");
W("**Acceptance test I run on receipt:** assemble the parts on the rig at rest and compare against the reference. If the figure matches, the pivots are right. If a limb floats away from its joint, that part's joint position was off and only that one part needs redoing.");

console.log(out.join("\n"));
