// GENERATED from fourth_forms_all.json (172 species). Star-4 name, title, description.
// Loaded before data.js. data.js copies these onto SP when the species exists.
(typeof window !== "undefined" ? window : globalThis).GD_FOURTH = {
  cind: ["Infernalotl", "Magmalotl Prime", "Elder fire dragon: huge flame-edged wings, obsidian horn crown, lava-veined scales and a ring of fire behind the head."],
  pyrp: ["Helivixen", "Solvixen Aureate", "Nine-tailed sun fox, tails ending in flame plumes, golden mantle."],
  bubb: ["Tsunamotter", "Tsunotter Regent", "Otter lord riding a standing wave of water, pearl crest."],
  shel: ["Atollashell", "Leviashell Colossus", "Island-sized shell with a coral reef and waterfall."],
  sprt: ["Verdalord", "Verdalop Eternal", "Giant hare with a tree-of-life antler crown, petals orbiting."],
  moss: ["Sporearch", "Sporeking Overgrowth", "Fungal forest on a huge mossy back, glowing spores."],
  sprk: ["Tempestquill", "Stormquill Tempest", "Quills lengthened into a storm halo, arcs between quills."],
  buzz: ["Tempestarch", "Tempestqueen Apex", "Giant storm bee with crystalline lightning wings."],
  pebb: ["Titanolith", "Titanite Monolith", "Mountain-sized stone beast with embedded crystals."],
  crys: ["Radiadon", "Prismadon Radiant", "Armadillo with a refracting gem carapace casting rainbow light."],
  wisp: ["Eclipanther", "Umbrapanther Eclipse", "Panther of living eclipse, ring of shadow around the head."],
  dusk: ["Nocturnova", "Eclipsar Nocturne", "Giant bat with a moon-eclipse wingspan and starry underwings."],
  emba: ["Calderoar", "Volcanoar Cataclysm", "Boar with a small volcano on its back, tusks of magma."],
  emfl: ["Pyrolantern", "Pyrolumen Beacon", "Lantern firefly whose body is a lighthouse of flame."],
  emgo: ["Cratercrab", "Calderacrab Leviathan", "Crab with a cauldron-crater shell erupting lava."],
  emph: ["Phoenexara", "Phoenexa Rebirth", "Phoenix in mid-rebirth, trailing sun-feathers."],
  emdr: ["Heliowyrm", "Solarwyrm Dominion", "Dragon wreathed in a corona of fire."],
  tifr: ["Monsoonarch", "Monsoad Tempest", "Giant frog with a storm-cloud back and rain curtains."],
  tijl: ["Luminaquall", "Abyssquall Luminous", "Deep-sea jelly with a cathedral of glowing tendrils."],
  tish: ["Maelstromaw", "Tidalmaw Apex", "Megalodon-like shark with riptide fins."],
  tisq: ["Krakenarch", "Krakenos Abyssal", "Leviathan squid with wreck-hugging tentacles."],
  tiwh: ["Oceanarch", "Oceanos Primordial", "Titanic armoured sky whale carrying a coral-reef kingdom with waterfalls, barnacle armour and a constellation belly."],
  blbe: ["Brambletitan", "Bramblehorn Titan", "Beetle with a thorn-crown and flowering shell."],
  blfl: ["Eldenwolf", "Gardenwolf Sovereign", "Wolf whose mane is a blooming garden."],
  blcm: ["Jungleoracle", "Junglesage Ancient", "Chameleon sage grown with jungle orchids."],
  bldr: ["Worldstag", "Elderstag Worldtree", "Stag whose antlers are a full canopy."],
  blmn: ["Orchimantis", "Petalmantis Empress", "Orchid mantis with a huge blossom fan."],
  vosn: ["Stormcitadel", "Thundershell Citadel", "Snail with a lightning-rod tower shell."],
  vohu: ["Thunderalpha", "Thunderfang Alpha", "Wolf with ribbons of lightning for a mane."],
  vobi: ["Cataclysroc", "Thunderroc Cataclysm", "Majestic thunderbird with a huge wingspan of layered lightning feathers, golden chest plates and a storm of violet-blue energy."],
  voro: ["Teslacolossus", "Teslahorn Colossus", "Rhino with a coil horn crackling arcs."],
  voli: ["Stormtyrant", "Stormking Tyrant", "Lion with a mane of thunderclouds."],
  stmo: ["Seismomole", "Quakemole Titan", "Giant mole carrying crystal boulders."],
  stgo: ["Apexram", "Summitram Ascendant", "Goat-ram on a peak, glacial crags in the horns."],
  stsc: ["Dunescorpex", "Sandstormer Dune King", "Scorpion with a sandstorm tail."],
  stbe: ["Primeursa", "Mountainursa Primeval", "Bear that is itself a mountain, with a waterfall."],
  stli: ["Pillarlion", "Templelion Guardian", "Temple-guardian lion with a pillar mane."],
  shra: ["Noctarch", "Nightmonarch Crowned", "Raven king with a crown of feathers and stars."],
  shsp: ["Starweaver", "Nightspinner Weaver", "Spider weaving constellations."],
  shdo: ["Underhound", "Grimhound Underking", "Hound with spectral chains of smoke."],
  shwr: ["Hexlich", "Hexmonarch Lich", "Grand hex-wraith with orbiting sigils."],
  shse: ["Nyxabyssal", "Nyxleviathan Abyssal", "Colossal coiling shadow serpent with a flared hood of glowing cyan runes, a starry smoke body and orbiting rune sigils."],
  frpe: ["Aurorimperor", "Auroramperor Majestic", "Emperor penguin lit by aurora curtains."],
  frst: ["Blizzmarshal", "Blizzstoat Marshal", "Stoat in a blizzard cloak."],
  frwa: ["Glacitusk", "Bergtusk Titan", "Walrus with an iceberg tusk crown."],
  frow: ["Celestowl", "Aurorowl Celestial", "Owl with aurora wings."],
  frmm: ["Glacialith", "Glacitan Ancient", "Mammoth cloaked in glacier."],
  frfl: ["Cryosovereign", "Cryomonarch Prime", "Giant snowflake lord with a crown of crystal."],
  frsa: ["Apexsaber", "Rimesaber Apex", "Sabertooth with a frozen-sky mane."],
  frdr: ["Cryowyrm", "Cryonarch Wyrm", "Ice dragon with crystal wings."],
  gahu: ["Zenithstrike", "Galestrike Zenith", "Hunter-hawk of gale-cloaked wings."],
  gash: ["Cumuloram", "Stormram Thundercloud", "Ram with a storm-cloud fleece."],
  gafe: ["Maelstromex", "Tornadex Maelstrom", "Ferret in a living tornado."],
  gamt: ["Mantarch", "Stratomanta Sovereign", "Sky manta with an aurora of cloud."],
  gagr: ["Imperigriff", "Stormgriffin Imperator", "Griffin with lightning-wind wings."],
  gadl: ["Galebloom", "Galeflower Bloom", "Dandelion spirit with a shower of seeds."],
  gaki: ["Ninekitsune", "Stormkitsune Nine", "Nine-tailed wind fox."],
  gase: ["Skydraco", "Skysovereign Draco", "Sky serpent coiled through clouds."],
  mecr: ["Fortresscrab", "Ironmonarch Fortress", "Crab-fortress with turrets of plates."],
  mean: ["Colossant", "Titanant Colossus", "Ant with titanium plating."],
  mesc: ["Pharaoscarab", "Auricscarab Pharaoh", "Golden scarab with gilded wings."],
  mepa: ["Citadelin", "Bastiongolin Citadel", "Pangolin as a walled castle."],
  mewf: ["Lunargent", "Argentwolf Moonforged", "Silver wolf with a moon-ring halo."],
  mest: ["Forgestag", "Titanstag Forge", "Stag with forged-antler arches."],
  mebu: ["Adamantitan", "Adamantor Juggernaut", "Bull with adamantine plates and forge-glow."],
  myun: ["Radiancorn", "Celesticorn Radiant", "Unicorn with a nebula mane."],
  myor: ["Omnioracle", "Oracleye Omniscient", "Floating eye with rings of orbiting runes."],
  mydf: ["Empyreafly", "Aurorafly Empyrean", "Butterfly with aurora-sky wings."],
  myqi: ["Divinqilin", "Skyqilin Divine", "Qilin with cloud scales and star fire."],
  mybe: ["Celestursa", "Lunarsa Celestial", "Moon bear with a halo of crescents."],
  mysh: ["Nebulamarine", "Cosmarine Nebula", "Sea-star creature wearing a nebula."],
  mydr: ["Stardrakon", "Astralon Stardrake", "Dragon of constellations and nebula wings."],
  emmk: ["Ignisimius", "Magmacaque Solar King", "A colossal magma macaque lord with a huge sweeping crown of living flame, obsidian shoulder plates veined with lava, a long burning tail and a molten glow in its chest."],
  emkg: ["Solarroo", "Pyrobound Sunleaper", "A towering sun kangaroo mid-bound with a blazing comet trail behind its glowing tail, golden molten armour plates, a corona of fire behind its head and heat-white feet."],
  emcp: ["Calderabara", "Magmabara Caldera Sage", "A gigantic volcanic capybara lord lounging in a vast lava caldera spring with a ring of glowing basalt stones, towering plumes of steam and fire, molten rivers on its fur and a crown of glowing coals."],
  emto: ["Citadelforge", "Citadelforge Eternal Hearth", "A colossal fortress tortoise bearing a whole glowing forge-citadel on its shell with multiple chimneys, rivers of lava running down the shell plates and a halo of embers and smoke."],
  embf: ["Solarbison", "Solarbison Volcanic Herdlord", "A colossal solar bison charging with a hump that is a small erupting volcano, huge curved horns made of glowing magma, a mane of living flame and trailing embers and ash."],
  emhc: ["Solhearth", "Solhearth Hearthkeeper", "A majestic hearth-goddess cat with three long flame-tipped tails, a golden glowing ember mantle, a ring of floating hearth embers and a bed of glowing coals under it, serene and warm."],
  emmo: ["Luminarch", "Luminarch Candle Seraph", "A colossal lighthouse moth with a vast candelabra of wings holding dozens of flames, a halo of golden light, rivers of molten golden wax and a glowing sun at its chest."],
  emsp: ["Heliomacaw", "Heliomacaw Dawn Herald", "A colossal sun macaw with huge wings of blazing sun feathers, a radiant disc of golden light behind its head, extremely long flame tail plumes and glowing golden talons."],
  emgk: ["Heliogecko", "Heliogecko Sunbasker", "A giant basking sun gecko with a vast sunburst frill like a blazing sun disc, glowing molten stripes along its whole body, heat waves rising off it and golden glowing toes."],
  empc: ["Solarpavo", "Solarpavo Wheel of Suns", "A colossal phoenix-like fire peacock with a gigantic wheel of blazing feathers like a sun behind it, golden feather eye-spots shining as fireballs, a crown crest of flame and trailing sparks."],
  tinw: ["Leviahorn", "Leviahorn Tidal Unicorn", "A colossal leviathan narwhal rising from a giant wave, its great spiral horn glowing with a swirling cyan whirlpool, pearl plating along its back, a crown of sea foam and bubbles around it."],
  tior: ["Tempestorca", "Tempestorca Storm Breacher", "A titanic tempest orca bursting out of a storm wave, glowing aqua currents flowing along its body, a huge crown dorsal fin like a blade of water, rings of bubbles and spray orbiting it."],
  tims: ["Chromatitan", "Chromatitan Prism Breaker", "A colossal chromatic shrimp titan with glittering prism armour casting rainbow light, enormous club claws wreathed in glowing shockwave bubbles, a coral-crystal crest and a spiked fan tail."],
  tioc: ["Octarch", "Octarch Inkweaver Regent", "A gigantic deep-sea octopus sovereign with huge tentacles drawing great glowing ink sigils and whirlpools around it, bioluminescent teal and blue spots all over, a crown of pearls and floating bubbles."],
  tisa: ["Seraphim", "Seraphim Abyssal Angel", "A radiant colossal sea seraph with a vast spread of translucent glowing fin-wings in layers, a halo ring of water, ribbons of light, a blazing golden core and tiny orbiting bubbles."],
  time: ["Seamanatee", "Seamanatee Lagoon Sovereign", "A gigantic lagoon manatee monarch carrying a whole floating lily-pad garden with blooming water lilies on its back, glowing cyan ripples, rings of luminous bubbles and a pearl crest."],
  ticl: ["Abyssearl", "Abyssearl Pearl Bastion", "A colossal abyssal clam fortress with a vast coral-encrusted shell that opens like a gate around an enormous radiant glowing pearl, rings of bubbles, light beams and drifting deep-sea sparkle."],
  tise: ["Tidemonarch", "Tidemonarch Pearl King", "A majestic colossal sea lion monarch balancing a huge glowing bubble pearl on its nose, a cascade of bubble necklaces, a wave crown, glowing aqua water ribbons flowing around it."],
  tist: ["Pentastar", "Pentastar Ocean Phoenix", "A colossal royal starfish with arms like a sunburst of glowing coral spires, one arm blooming with new sparkling arms, a ring of floating bubbles and a luminous star core."],
  tina: ["Nautilarch", "Nautilarch Spiral Elder", "A gigantic ancient nautilus whose spiral shell chambers each glow like portals of water light, a halo of spiral currents, long flowing luminous tentacles and floating pearls orbiting it."],
  blmg: ["Briarmongoose", "Briarmongoose Thorn Sovereign", "A colossal thornwood mongoose lord with a mane of thick vines and giant blossoming flowers, a huge tail covered in sword-length thorns like a briar whip, glowing green spores drifting around it."],
  blrc: ["Sylvacoon", "Sylvacoon Canopy Trickster", "A towering forest-spirit raccoon with a giant crown of oak leaves and acorns, a great cape of ferns and flowers, a huge ringed tail of layered leaves and glowing green spores."],
  blpi: ["Nepenthrone", "Nepenthrone Nectar Monarch", "A colossal royal pitcher plant with a grand crown of several lidded pitchers, hanging vine tendrils, a glowing golden nectar fountain and swirling green spores and fireflies around it."],
  blmo: ["Selenabloom", "Selenabloom Moonpetal Empress", "A gigantic moon-bloom moth with vast layered petal wings like a giant glowing flower in bloom, a crescent crown, shimmering golden pollen clouds and glowing moon-green eye-spots."],
  blcr: ["Hanacrane", "Hanacrane Blossom Celestial", "A colossal celestial blossom crane with enormous wings of ivory and pale-gold petals, a vast trailing train of white flowers, drifting white petals orbiting it and a halo of golden pollen."],
  blhi: ["Marshpotamus", "Marshpotamus Swamp Sovereign", "A gigantic marsh hippo king carrying a whole lush swamp island on its back with blooming lotuses, reeds, a miniature tree and fireflies, with its frog friend on its crown and glowing green mist."],
  blen: ["Worldoak", "Worldoak Ancient Guardian", "A colossal world-oak guardian with a gigantic spreading canopy crown of leaves, a trunk body with glowing green sap veins, root legs, hanging acorns and fireflies, moss and flowers all over."],
  blld: ["Ladybloom", "Ladybloom Garden Empress", "A colossal blossom ladybug with a vast shell that is a giant blooming flower bed of many flowers, wings of translucent petals spread, a ring of floating petals and golden pollen."],
  blpa: ["Pandarch", "Pandarch Bamboo Sage", "A colossal guardian panda with a towering bamboo forest growing on its back, glowing jade-green rune lines on its fur, a halo of bamboo leaves and drifting petals, majestic calm pose."],
  blsn: ["Edenshell", "Edenshell Paradise Gardener", "A gigantic paradise snail with an enormous spiral shell that is a floating garden of Eden with trees, waterfalls, blooming flowers and glowing mushrooms, a trail of flowers behind it and sparkling dew drops."],
  vosq: ["Tempestirrel", "Tempestirrel Stormtail King", "A colossal tempest squirrel with a vast tail like a storm cloud trailing branching lightning, a crown of electric arcs around its head, glowing yellow-blue bolt markings and crackling static sparks."],
  voch: ["Thundercheetah", "Thundercheetah Bolt Sprinter", "A colossal thunder cheetah mid-sprint trailing a branching lightning storm behind it, glowing electric bolt spots, a mane of crackling electricity and blue-white arcs between its paws."],
  voal: ["Thunderalpaca", "Thunderalpaca Stormfleece Regent", "A colossal storm-cloud alpaca whose wool is a vast thundercloud crackling with lightning, a glowing golden fringe like a crown, electric blue arcs and floating sparks, serene regal pose."],
  vogi: ["Stormgiraffe", "Stormgiraffe Skypiercer", "A colossal storm giraffe whose neck rises into thunderclouds, two huge lightning-rod horns channelling a bolt of lightning between them, glowing yellow patches, a crackling electric mane and blue-white sparks."],
  voyk: ["Stormyak", "Stormyak Thunderherd Titan", "A colossal thunder yak with a massive storm-charged shaggy coat shedding bolts of lightning, huge curved horns crowned with electric arcs, glowing yellow-blue fur strands and a thundercloud mantle."],
  vogo: ["Titanilla", "Titanilla Tesla Colossus", "A colossal titan gorilla with a chest full of giant glowing tesla coils firing lightning arcs, a mantle of crackling electricity, silver fur streaked with electric blue and a blazing yellow reactor core."],
  voha: ["Dynamo", "Dynamo Prime Generator", "A colossal dynamo hamster powering a vast gleaming wheel like a thunder generator, rings of lightning around the wheel, floating glowing light orbs and arcs of electricity, joyful pose."],
  voct: ["Symphonicket", "Symphonicket Thunder Maestro", "A colossal symphony cricket with enormous wings like glowing speaker membranes pulsing concentric rings of lightning sound waves, crown antennae crackling with arcs, glowing yellow and blue patterns."],
  vogw: ["Lumiserpent", "Lumiserpent Radiant Coil", "A colossal luminous serpent-worm coiling in the air with a gigantic radiant lightbulb tail like a sun, glowing segments linked by electric arcs, rings of light and floating light orbs."],
  vosl: ["Teslarch", "Teslarch Storm Sage", "A colossal storm-sage sloth, shaggy storm-cloud fur crackling with lightning, a halo of three concentric glowing electric rings behind it, huge curved glowing claws, yellow tesla crystals growing from its back like a crown, serene face."],
  stgl: ["Obsidiangila", "Obsidiangila Volcanic Tyrant", "A colossal obsidian gila monster with jagged obsidian crystal plates along its back, molten amber seams glowing across its body, a huge basalt-spiked tail and drifting embers."],
  stje: ["Mirajerboa", "Mirajerboa Dune Dancer", "A colossal mirage jerboa leaping above a spiralling sand vortex, giant ears like sails with golden desert patterns, sparkling sand ribbons, shimmering heat mirage and floating sandstone fragments."],
  stca: ["Monolith", "Monolith Ancient Cairn", "A colossal floating monolith cairn of giant balanced standing stones with glowing amber carved runes, a serene wise face, rings of orbiting rock fragments and a halo of crystal."],
  stsx: ["Pharasphinx", "Pharasphinx Eternal Riddler", "A colossal pharaonic sphinx cat with an enormous sandstone and gold sun headdress, glowing amber hieroglyph-free carved patterns, a halo of sun rays made of sand, majestic wise pose."],
  stwm: ["Mountwombat", "Mountwombat Rockback Titan", "A colossal mountain wombat with an entire rocky mountain range on its back with crystal peaks, glowing amber crystal veins, thick stony fur and rubble circling it."],
  stak: ["Citadelodon", "Citadelodon Living Fortress", "A colossal fortress ankylosaur with a battlement-like armour of stone towers and spikes, a gigantic crystal boulder club tail, glowing amber cracks across its plates and floating rock shards."],
  stmk: ["Sunpharaoh", "Sunpharaoh Dune Eternal", "A colossal sun-pharaoh meerkat, towering and upright, a huge golden sun-disc halo of sandstone and gold behind its head, a layered stone mantle, glowing amber carvings and floating sandstone shards orbiting it."],
  stcm: ["Miragecamel", "Miragecamel Oasis Caravaner", "A colossal mirage camel carrying glowing floating oasis ponds on its humps with palm trees, shimmering waterfalls, golden desert patterns and a heat mirage halo."],
  sthy: ["Summithyrax", "Summithyrax Cliff Sovereign", "A colossal summit hyrax perched on a towering cliff peak with a sun-disc halo of golden stone, crystal ridges all along its back, glowing sunstones orbiting it and swirling dust."],
  sttr: ["Primevaltri", "Primevaltri Fossil Emperor", "A colossal primeval trilobite with enormous plated shell like an ancient fossil temple, glowing amber fossil patterns, huge spined crest, floating rock fragments and sparkling crystal growths."],
  shwe: ["Umbramustela", "Nightermine Void Stalker", "Colossal night-hooded ermine with a star-filled smoke mantle and a crescent of cyan starlight."],
  shhy: ["Cacklord", "Cacklord Dread Chorus", "Gigantic cackling hyena lord with a towering mane of roiling black smoke and cyan glow."],
  shnm: ["Eclipsemare", "Dreadmare Eclipse Rider", "Rearing colossal eclipse-mare with smoke mane, silver crescent and an eclipse ring behind the head."],
  shpb: ["Abysspill", "Umbrapill Dark Bulwark", "Colossal pillbug in a giant armoured ball of layered black-navy plates with cyan seams."],
  shmi: ["Hoardmimic", "Vaultmimic Treasure Terror", "Colossal ornate hoard-mimic chest overflowing with gold and cyan gems, long tongue and clawed legs."],
  shbl: ["Dirgebell", "Tollwraith Funeral Knell", "Colossal ancient dirge-bell with orbiting ghost bells and cyan shockwave rings."],
  shdm: ["Oneiromouse", "Somnimouse Dream Sovereign", "Gigantic dormouse wrapped in a vast starry mist-cloud blanket and nightcap."],
  shnu: ["Tenebranch", "Tenebranch Starfrill", "Colossal nebula nudibranch with a starry frilled cape and a crown of luminous gills."],
  shta: ["Moontarsier", "Moontarsier Lunar Watcher", "Colossal tarsier with twin-moon eyes, crescent ears and a moonlight halo."],
  shnj: ["Eclipjar", "Gloamjar Twilight Wing", "Colossal nightjar with twilight-sky wings, streaming tail and a dark moon disc."],
  frlx: ["Blizzlynx", "Glaciolynx Blizzard Hunter", "Colossal glacier lynx with a mane of long ice crystals and aurora-blue trim."],
  frwv: ["Blizzverine", "Glaciverine Rimeclaw Tyrant", "Colossal wolverine with jagged ice claws and glacier plates in a swirling blizzard."],
  frrp: ["Cryoraptor", "Cryoraptor Aurora Stormclaw", "Colossal feathered raptor with an ice-crystal crest, frost-feather arms and an aurora behind it."],
  frhr: ["Auroreus", "Auroreus Moonrune Sage", "Colossal moon-hare sage with halo of glowing moon-rune circles and aurora ear ribbons."],
  frki: ["Cryokoidrake", "Cryokoidrake Aurora Ascendant", "Colossal koi-dragon with ice-white scales and a tail streaming a vast aurora."],
  frmo: ["Mammuskox", "Mammuskox Glacier Patriarch", "Colossal musk ox with an icicle skirt, glowing ice-horns and glacier chunks on its hump."],
  frse: ["Cryolephant", "Cryolephant Iceberg Bulwark", "Colossal elephant seal in glacier-ice plate armour with icebergs on its back."],
  frpf: ["Auropuffin", "Auropuffin Snowflake Herald", "Colossal puffin with wide ice-crystal wings, a glowing snowflake beak and an ice-feather crown."],
  frsm: ["Glaciosage", "Glaciosage Onsen Elder", "Colossal sage snow monkey meditating in a tiered glowing-blue spring under aurora ribbons."],
  frsd: ["Winterbloom", "Winterbloom Aurora Carillon", "Colossal winter-bloom with a crown of glowing bell blossoms, ice petals and aurora light."],
  gagz: ["Tempestgazelle", "Tempestgazelle Cyclone Leaper", "Colossal gazelle leaping on a cyclone with swept-back wind-wrapped horns."],
  gaff: ["Aeropiscis", "Aeropiscis Zephyr Leviathan", "Colossal sky-fish with sail-like wing-fins in a vortex of mint wind ribbons."],
  galy: ["Tempestlyre", "Tempestlyre Harpwind Maestro", "Majestic lyrebird with a gigantic harp-tail of glowing wind strings."],
  gact: ["Stratotort", "Stratotort Thunderhead Elder", "Colossal sky-turtle carrying a stormy cloud mountain with rain curtains."],
  gapf: ["Cyclonimbus", "Cyclonimbus Eyewall Behemoth", "Colossal storm-balloon puffer with a whirlwind, jade plates and an eye-of-the-storm belly."],
  gaib: ["Aeribex", "Aeribex Jetstream Warden", "Colossal ibex on a peak with sweeping horns wrapped in jet-stream ribbons."],
  gael: ["Tempestphant", "Tempestphant Skysail Colossus", "Colossal elephant with giant sail-like ears gliding through wind and clouds."],
  gasw: ["Haloswallow", "Haloswallow Skyhalo Streak", "Colossal swallow with swept wings, long streamers and a luminous wind halo."],
  gado: ["Halcyon", "Halcyon Zephyr Seraph", "Majestic colossal dove with silver-mint streamer tail and a soft halo."],
  gapw: ["Cyclonwheel", "Cyclonwheel Windmill Bloom", "Colossal windmill-bloom with concentric spinning petal rings in a cyclone."],
  mekf: ["Argentfisher", "Argentfisher Skyplunge Striker", "Colossal jet-kingfisher in a dive with titanium plates and a fin-like silver crest."],
  meow: ["Horologowl", "Chronowl Horologe Sovereign", "Colossal owl with gear-feather wings, a clock face chest and orbiting cogs."],
  mefn: ["Orbitfennec", "Orbitfennec Array Seer", "Colossal fennec with giant radar-dish ears, rotating rings and signal waves."],
  meot: ["Chronolith", "Chronolith Celestial Orrery", "Colossal tortoise carrying an immense armillary orrery of nested spinning rings."],
  mepc: ["Adamantpine", "Adamantpine Mirrorquill Fortress", "Colossal porcupine with a gigantic radiating crest of mirror chrome quills."],
  memd: ["Adamantmastiff", "Adamantmastiff Ironjaw Warlord", "Colossal mastiff in thick riveted adamantine armour with a huge steel jaw."],
  meko: ["Argentkoala", "Argentkoala Mirrorgrove Sage", "Colossal silver koala hugging a giant chrome eucalyptus tree with gold leaves."],
  memo: ["Chronomouse", "Chronomouse Grand Cabinet", "Colossal mouse with a giant ornate winding key and an open music box on its back."],
  megw: ["Auricbutterfly", "Auricbutterfly Gilded Emperor", "Colossal butterfly with gold filigree wings, sapphire eye spots and a gold crest."],
  mewe: ["Horolophant", "Horolophant Clocktower Titan", "Colossal wind-up elephant carrying a brass clock-tower of turning gears."],
  mygk: ["Kaleidogecko", "Kaleidogecko Prism Sovereign", "Colossal gecko with a prism-crystal frill refracting rainbow beams."],
  mypm: ["Auroramorph", "Auroramorph Stained-Glass Empress", "Colossal butterfly with stained-glass kaleidoscope wings and a stardust trail."],
  mylm: ["Cosmolemur", "Cosmolemur Galactic Sovereign", "Colossal lemur sovereign with a galaxy-spiral tail, starlight mane and crescent halo."],
  myjk: ["Cosmojackal", "Cosmojackal Runemane Anubis", "Colossal jackal with a starlight rune-mane and a ring of floating glyphs."],
  mytp: ["Oneirotapir", "Oneirotapir Nebula Devourer", "Colossal tapir whose coat is a nebula sky, inhaling spirals of dream bubbles."],
  mytd: ["Eternitardi", "Eternitardi Void Wanderer", "Colossal tardigrade whose plated back is a galaxy with orbiting planets."],
  mymc: ["Mooncake", "Mooncake Lunar Emperor", "Colossal squishy moon rabbit in front of a giant silver moon disc."],
  mymo: ["Celestialmoose", "Celestialmoose Aurora Monarch", "Colossal moose with immense palmate antlers made of living aurora."],
  myfc: ["Cosmoneko", "Cosmoneko Fortune Sovereign", "Colossal fortune cat with a radiant gold paw and a halo of floating coins and stars."],
  myho: ["Seraphoe", "Seraphoe Radiant Crown", "Colossal hoopoe with a huge sun-like crown crest and spread striped wings."],
};
