/* Iron League — Heroes99 compositor.
   Sheets are 800×680. Sprites are NOT a uniform 80×68 grid; each frame is a
   measured rect with a foot anchor. See ANIM.md. */
(function (root) {
  const IL = root.IL = root.IL || {};
  const BASE = "assets/heroes99/";

  /* [x, y, w, h, ax, ay] — ax/ay is the foot point inside the crop.
     Generated by measuring every opaque pixel in the pack. */
  const FRAMES = [
    [19,3,46,33,22.02,30],[119,2,46,33,22.03,31],[218,2,47,33,23.03,31],[319,3,46,32,22.02,30],[420,4,45,31,21.02,29],[520,4,43,31,21.02,29],
    [13,43,45,32,27.86,30],[115,42,42,33,25.9,31],[216,42,40,33,24.9,31],[315,43,42,32,25.86,30],[414,44,44,31,26.86,29],[514,44,45,31,26.86,29],
    [24,84,41,31,16.91,29],[122,84,46,31,19.07,29],[219,83,46,32,21.96,30],[323,83,37,32,17.99,30],[420,84,46,32,21.03,29],[522,84,48,31,19.07,29],[621,84,47,31,20.25,29],[722,84,45,31,19.07,29],
    [12,125,46,30,28.62,28],[114,125,44,30,27,28],[215,124,42,31,26.17,29],[315,124,43,31,26.44,29],[417,125,40,30,24.45,28],[518,125,38,30,23.32,28],[617,125,40,30,24.21,28],[715,125,42,30,25.81,28],
    [13,163,45,33,28.02,30],[119,162,37,34,22.36,31],[222,162,31,35,19.01,31],[323,162,31,33,18.67,31],[423,162,32,34,18.69,32],[523,161,32,35,18.69,33],[623,161,32,35,18.69,33],[713,163,45,33,28.02,30],
    [4,203,49,32,37.17,30],[106,203,47,32,34.42,30],[210,203,64,32,32.66,30],[325,207,56,28,19.02,26],[425,207,54,29,19.02,26],[526,205,50,30,16.49,28],
    [21,245,35,30,20.67,28],[127,245,33,30,14.26,28],[223,247,53,28,19.47,26],[319,246,56,29,22.67,27],[419,247,37,28,22.67,26],[512,247,46,28,29.33,26],
    [20,283,49,32,21.02,30],[120,283,48,32,20.38,30],[223,285,68,30,19.66,28],[326,285,57,30,16.49,28],
    [5,323,49,34,37,32],[107,323,46,34,34.37,32],[211,321,64,35,31.59,33],[323,325,57,30,20.12,28],[423,325,55,30,20.12,28],[524,324,52,32,18.28,30],
    [21,363,49,34,20.98,32],[121,362,48,35,20.34,33],[223,364,68,32,19.59,30],[324,364,59,32,18.28,30],
    [18,403,47,32,23.02,30],[119,403,46,32,22.52,30],[220,403,43,32,21.52,30],[320,402,43,33,21.52,31],[420,402,43,33,21.52,31],
    [13,443,45,33,28.02,30],[121,443,54,32,20.95,30],[221,443,54,32,20.95,30],[321,443,54,32,20.95,30],[421,443,54,32,20.95,30],
    [13,483,45,33,28.02,30],[123,483,44,32,15.99,30],[225,483,39,32,14.53,30],[322,484,47,31,18.75,29],
    [18,526,47,30,22.26,27],[118,527,47,29,22.26,26],[224,535,39,21,20.07,19],[322,538,43,18,22.07,16],[422,541,42,15,22.07,13],
    [13,563,45,33,28.02,30],[115,566,43,29,27.13,27],[209,567,48,28,33.3,26],[309,566,48,29,33.3,27],[409,566,48,29,33.3,27],[520,564,37,31,20.9,29],[613,563,45,33,28.02,30],[713,563,45,33,28.02,30],
    [25,604,41,31,15.58,29],[123,604,40,31,16.81,29],[223,604,40,31,16.81,29],[323,604,40,31,16.81,29],[425,604,41,31,15.58,29],
    [17,644,42,31,26.17,29],[122,649,37,26,21.23,24],[229,656,29,19,13.71,17],[314,656,46,19,29.89,17],[419,655,41,20,22.46,18],[525,652,36,23,16.98,21],[627,647,37,28,17.46,26],[719,642,46,33,22.03,31]
  ];

  const images = new Map();
  const atlases = new Map();

  function loadImage(src) {
    if (images.has(src)) return images.get(src);
    const p = new Promise(function (resolve, reject) {
      const img = new Image();
      img.onload = function () { resolve(img); };
      img.onerror = function () { reject(new Error("Could not load " + src)); };
      img.src = src;
    });
    images.set(src, p);
    return p;
  }

  function layerPaths(parts) {
    const hair = parts.hair;
    const hc = parts.hairColor;
    const cloth = parts.cloth;
    const cc = parts.clothColor;
    const w = parts.weapon;
    const wc = parts.weaponColor || 1;
    const wbot = w === 5
      ? BASE + "weapon/weapon5/weapon5_bot/weapon5_c" + wc + "_bot.png"
      : BASE + "weapon/weapon" + w + "/weapon" + w + "_bot/weapon" + w + "_bot.png";
    const wtop = w === 5
      ? BASE + "weapon/weapon5/weapon5_top/weapon5_c" + wc + "_top.png"
      : BASE + "weapon/weapon" + w + "/weapon" + w + "_top/weapon" + w + "_top.png";
    const skin = BASE + "skin/skin_c" + parts.skin + ".png";
    const face = BASE + "face/face_c" + parts.face + ".png";
    const clothBot = BASE + "cloth/cloth" + cloth + "/cloth" + cloth + "_bot/cloth" + cloth + "_c" + cc + "_bot.png";
    const clothTop = BASE + "cloth/cloth" + cloth + "/cloth" + cloth + "_top/cloth" + cloth + "_c" + cc + "_top.png";
    const hairBot = BASE + "hair/" + hair + "/" + hair + "_bot/" + hair + "_c" + hc + "_bot.png";
    const hairTop = BASE + "hair/" + hair + "/" + hair + "_top/" + hair + "_c" + hc + "_top.png";
    /* Shirts, pants, and boots live in cloth_bot. Most cloth_top sheets are
       empty (pauldrons and cape fronts only). Draw the garment on the body.
       Hair and weapon still split behind and in front. */
    return [wbot, skin, face, clothBot, clothTop, hairBot, hairTop, wtop];
  }

  function keyOf(parts) {
    return [
      parts.skin, parts.face, parts.hair, parts.hairColor,
      parts.cloth, parts.clothColor, parts.weapon, parts.weaponColor || 1
    ].join(".");
  }

  function compose(parts) {
    const key = keyOf(parts);
    if (atlases.has(key)) return atlases.get(key);
    const job = Promise.all(layerPaths(parts).map(loadImage)).then(function (imgs) {
      const canvas = document.createElement("canvas");
      canvas.width = 800;
      canvas.height = 680;
      const ctx = canvas.getContext("2d");
      ctx.imageSmoothingEnabled = false;
      for (let i = 0; i < imgs.length; i++) ctx.drawImage(imgs[i], 0, 0);
      return canvas;
    });
    atlases.set(key, job);
    return job;
  }

  function draw(ctx, atlas, frame, x, y, scale, facing) {
    if (!atlas || !frame) return;
    const f = FRAMES[frame - 1];
    if (!f) return;
    const s = scale || 4;
    ctx.save();
    ctx.translate(Math.round(x), Math.round(y));
    ctx.scale(facing < 0 ? -1 : 1, 1);
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(atlas, f[0], f[1], f[2], f[3], Math.round(-f[4] * s), Math.round(-f[5] * s), f[2] * s, f[3] * s);
    ctx.restore();
  }

  IL.FRAMES = FRAMES;
  IL.hero = {
    keyOf: keyOf,
    compose: compose,
    draw: draw,
    layerPaths: layerPaths
  };
})(typeof window !== "undefined" ? window : globalThis);
